"""Turn the handwritten card title into SVG glyph outlines, so the page can trace each letter.

Usage:
    python tools/make_title_svg.py <MrsSaintDelafield-Regular.ttf> <GreatVibes-Regular.ttf>

Writes the SVG between the <!-- title-art:start --> / <!-- title-art:end --> markers in
index.html. Fonts: Mrs Saint Delafield for the text, with the capital G borrowed from
Great Vibes (at 80%) because Delafield's G is hard to read. Both are SIL OFL, from
https://github.com/google/fonts.
"""
import os
import re
import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

LINES = ["Armada", "Grand Banquet"]
SIZE = 100          # font size in SVG units
LINE_GAP = 1.02     # baseline-to-baseline, in em (matches the old CSS line-height)
G_SCALE = 0.8
PAD = 6

HERE = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(HERE, "..", "index.html")


class Face:
    def __init__(self, path, scale=1.0):
        self.font = TTFont(path)
        self.glyphs = self.font.getGlyphSet()
        self.cmap = self.font.getBestCmap()
        self.k = SIZE * scale / self.font["head"].unitsPerEm

    def glyph(self, ch):
        name = self.cmap[ord(ch)]
        return name, self.font["hmtx"][name][0] * self.k


def layout(line, main, g_face):
    """Place each character; returns [(char, face, glyphname, x)] and the advance width."""
    x = 0.0
    placed = []
    for ch in line:
        face = g_face if ch == "G" else main
        name, adv = face.glyph(ch)
        if ch != " ":
            placed.append((ch, face, name, x))
        x += adv
    return placed, x


def outline(face, name, x, baseline):
    pen = SVGPathPen(face.glyphs)
    # font units are y-up; flip into SVG's y-down space and position the glyph
    face.glyphs[name].draw(TransformPen(pen, (face.k, 0, 0, -face.k, x, baseline)))
    bounds = BoundsPen(face.glyphs)
    face.glyphs[name].draw(TransformPen(bounds, (face.k, 0, 0, -face.k, x, baseline)))
    return pen.getCommands(), bounds.bounds


def main():
    main_face = Face(sys.argv[1])
    g_face = Face(sys.argv[2], G_SCALE)

    lines = []
    for i, text in enumerate(LINES):
        placed, width = layout(text, main_face, g_face)
        baseline = i * SIZE * LINE_GAP
        glyphs = [(ch, *outline(face, name, x, baseline)) for ch, face, name, x in placed]
        ink = [b for _, _, b in glyphs if b]
        x0, x1 = min(b[0] for b in ink), max(b[2] for b in ink)
        lines.append((glyphs, x0, x1))

    # centre each line on its ink, then fit the viewBox around everything
    widest = max(x1 - x0 for _, x0, x1 in lines)
    out_lines = []
    all_bounds = []
    for glyphs, x0, x1 in lines:
        shift = (widest - (x1 - x0)) / 2 - x0
        out_lines.append((shift, glyphs))
        for _, _, b in glyphs:
            if b:
                all_bounds.append((b[0] + shift, b[1], b[2] + shift, b[3]))
    vx0 = min(b[0] for b in all_bounds) - PAD
    vy0 = min(b[1] for b in all_bounds) - PAD
    vx1 = max(b[2] for b in all_bounds) + PAD
    vy1 = max(b[3] for b in all_bounds) + PAD

    rows = []
    for n, (shift, glyphs) in enumerate(out_lines):
        paths = "\n".join(
            f'            <path data-char="{ch}" d="{d}"/>' for ch, d, _ in glyphs if d
        )
        rows.append(f'          <g class="title-line" transform="translate({shift:.2f} 0)">\n{paths}\n          </g>')

    w, h = vx1 - vx0, vy1 - vy0
    svg = f'''<!-- title-art:start (generated by tools/make_title_svg.py) -->
      <svg class="title-art" viewBox="{vx0:.1f} {vy0:.1f} {w:.1f} {h:.1f}" aria-hidden="true">
        <defs>
          <linearGradient id="titleInk" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0" stop-color="#34679f"/><stop offset=".4" stop-color="#173e78"/>
            <stop offset=".65" stop-color="#3f76b6"/><stop offset="1" stop-color="#16386e"/>
          </linearGradient>
          <pattern id="titleFrost" patternUnits="userSpaceOnUse" width="200" height="132">
            <image href="assets/frost.webp" width="200" height="132"/>
          </pattern>
          <!-- Ink gradient with a faint frost texture on top, as a single fill. Keeping the
               letters as plain, directly rendered paths (no <use> copies) means animating them
               is cheap and works in every browser. -->
          <!-- pattern contents are positioned relative to the tile's own top-left corner -->
          <pattern id="titleFill" patternUnits="userSpaceOnUse" x="{vx0:.1f}" y="{vy0:.1f}" width="{w:.1f}" height="{h:.1f}">
            <rect width="{w:.1f}" height="{h:.1f}" fill="url(#titleInk)"/>
            <rect width="{w:.1f}" height="{h:.1f}" fill="url(#titleFrost)" opacity=".3"/>
          </pattern>
        </defs>
        <g class="title-glyphs" fill="url(#titleFill)" stroke="#2b5c9a" stroke-width="0.7" stroke-linejoin="round">
{chr(10).join(rows)}
        </g>
      </svg>
      <!-- title-art:end -->'''

    html = open(INDEX, encoding="utf-8").read()
    pattern = re.compile(r"<!-- title-art:start.*?<!-- title-art:end -->", re.S)
    if not pattern.search(html):
        sys.exit("index.html has no title-art markers")
    html = pattern.sub(lambda _: svg, html)
    open(INDEX, "w", encoding="utf-8").write(html)
    count = sum(len(g) for _, g in out_lines)
    print(f"wrote {count} glyphs, viewBox {w:.0f} x {h:.0f}")


if __name__ == "__main__":
    main()
